# Generated by Django 3.2 on 2021-08-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_participante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participante',
            old_name='name',
            new_name='apellido',
        ),
        migrations.AddField(
            model_name='participante',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
