# Generated by Django 3.2 on 2021-08-16 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0005_auto_20210816_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntasrespondidas',
            name='quizUser',
        ),
        migrations.AddField(
            model_name='participante',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Puntaje Total'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='Tiepo',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='categoria',
            field=models.CharField(choices=[('General', 'General'), ('Historia', 'Historia'), ('Geografia', 'Geografia'), ('Ciencia', 'Ciencia'), ('Deporte', 'Deporte'), ('Arte', 'Arte'), ('Entretenimiento', 'Entretenimiento')], default='General', max_length=15),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.CharField(choices=[('Facil', 'Facil'), ('Normal', 'Normal'), ('Dificil', 'Dificil')], default='Facil', max_length=10),
        ),
        migrations.AddField(
            model_name='preguntasrespondidas',
            name='participante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='aplicacion.participante'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='max_puntaje',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Maximo Puntaje'),
        ),
        migrations.AlterField(
            model_name='preguntasrespondidas',
            name='puntaje_obtenido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Puntaje Obtenido'),
        ),
        migrations.DeleteModel(
            name='QuizUsuario',
        ),
    ]
