# Generated by Django 3.2 on 2021-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_auto_20210816_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='Tiepo',
        ),
        migrations.AlterField(
            model_name='participante',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Puntaje Total'),
        ),
    ]
